name: API Test Deploy to WeChat Cloud Run

on:
  push:
    branches:
      - test

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    env:
      WXCLOUD_SERVICE_NAME: ${{ secrets.WXCLOUD_TEST_SERVICE_NAME }}
      WXCLOUD_APPID: ${{ secrets.WXCLOUD_APPID }}
      WXCLOUD_CLI_SECRET: ${{ secrets.WXCLOUD_CLI_SECRET }}
      WXCLOUD_ENVID: ${{ secrets.WXCLOUD_ENVID }}
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install @wxcloud/cli
        run: npm i -g @wxcloud/cli

      - name: Login @wxcloud/cli
        run: wxcloud login --appId="$WXCLOUD_APPID" --privateKey="$WXCLOUD_CLI_SECRET"

      - name: Deploy to WeChat Cloud Run
        run: wxcloud run:deploy --targetDir=. --dockerfile=Dockerfile --containerPort=3000 --envId="$WXCLOUD_ENVID" --serviceName="$WXCLOUD_SERVICE_NAME" --noConfirm --releaseType=FULL --remark="${{ github.event.head_commit.message || github.actor }}"
